# Site
repository: github.com/rachaelssmith
favicon: images/profile_rachael.jpg

# Content configuration version
version: 2

# Personal info
name: Rachael Smith
title: Data Scientist
email: smith.rachael@gmail.com
#website: rachaelssmith.github.io/rachael_smith_resume/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  rachaelssmith
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: rachael-s-smith
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: mywebsite
  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_rachael.jpg
about_content: | # this will include new lines to allow paragraphs
  *I am passionate about understanding my client's challenges and finding the story within the data that can drive businesses to make informed decisions.*
  
  Hi, my name's Rachael and I'm a data science student, I love math, programming and problem solving.  I love to dream big and am very self driven.  I don't see challenges as limits, I have a track record of going above and beyond to accomplish a goal, and leading a team along the way.  I am passionate about data, so you don't have to be.  I am experienced in statistics, business analytics and machine learning. Prior to studying Data Science, I founded a charter school and served as a Board Vice Chairman for 10 years gaining teamwork and leadership skills.  

  I am most skilled in: <mark>R</mark> and <mark>Python</mark>.  
  
  I also am skilled at <mark>SQL</mark>, <mark>Machine Learning</mark>, <mark>Excel</mark>, <mark>Power BI</mark>, <mark>R</mark>, and <mark>Tableau</mark>.

content:
 # - title: Projects # Title for the section
  #  layout: list # Type of content section (list/text)
   # content:
    #  - layout: top-middle
     #   title: Research and Business Development Center
      #  link: github.com/sproogen
        # link_text: Project Website
       # additional_links:
  #        - title:  Technical Project Lead
            #icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
        #  Working for Good2Go was a pleasure, what impressed me most is their ability to ask great questions and interest in our growth.
       # description: | # this will include new lines to allow paragraphs
         # - Client is utilizing <mark>Sales Forecasting</mark> tool used in business created in <mark>Power BI</mark>.
          #- Led group of students in <mark>Machine Learning</mark> and <mark>Time Series Prediction</mark> utilizing <mark>R</mark> and <mark>Python</mark>.
          #- Increased workflow efficiency by <mark>wrangling data </mark> in<mark>R</mark> & <mark>SQL</mark> from 40GB file sizes to 1 GB, and from 60 files to a single file.
 
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Brigham Young University - Idaho
        caption: 2018 - 2022
        sub_title: BS | Data Science <br> Minor | Business Analytics <br> Certificate | Machine Learning <br> GPA: 3.88
        quote: >
          The BYU-ID methodology encourages students to be proactive in their learning, become highly skilled, and to build up those around them.
        description: | # this will include new lines to allow paragraphs
          My time at BYU-ID, has ignited a spark for machine learning and statistical analysis. I also learned how to navigate personal goals, team projects, and working with tight deadlines. 

  - title: Data Science Lead Experience  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Research & Business Development Center
        caption: January 2021 - April 2021
        sub_title: Technicale Project Lead | Good2Go Forecasting
        quote: >
          Working to understand the client's needs while leading a team of students helped me better understand the value of collaboration, good communication, in meeting a deadline.
        description: | # this will include new lines to allow paragraphs
          - Client is utilizing <mark>Sales Forecasting</mark> tool used in business created in <mark>Power BI</mark>.
          - Led group of students in <mark>Machine Learning</mark> and <mark>Time Series Prediction</mark> utilizing <mark>R</mark> and <mark>Python</mark>.
          - Increased workflow efficiency by <mark>wrangling data </mark> in<mark>R</mark> & <mark>SQL</mark> from 40GB file sizes to 1 GB, and from 60 files to a single file.

      - layout: left
        title: Brigham Young University Idaho | Rexburg
        caption: September 2020 - December 2020
        sub_title: Intermediate Statistics <br> Teacher's Assistant & Tutor
        quote: >
          I loved helping students succeed and bring their ideas to life!
        description: | # this will include new lines to allow paragraphs
          - Supported students in understanding statistical testing and analysis.
          - Provided expertise in statistical modeling and data wrangling & data visualization using ggplot and tidyverse. 

  - title: Projects  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: list
        title: Research & Business Development Center
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Student Consultant | Good2Go Covid Data
        caption: September 2020 - December 2020
        quote: >
          Working for Good2Go was a pleasure, what impressed me most is their ability to ask great questions and interest in our growth.
        description: | # this will include new lines to allow paragraphs
          - Client is utilizing <mark>Sales Forecasting</mark> tool used in business created in <mark>Power BI</mark>.
          - Led group of students in <mark>Machine Learning</mark> and <mark>Time Series Prediction</mark> utilizing <mark>R</mark> and <mark>Python</mark>.
          - Increased workflow efficiency by <mark>wrangling data </mark> in<mark>R</mark> & <mark>SQL</mark> from 40GB file sizes to 1 GB, and from 60 files to a single file.

  - title: A Little More About Me
    layout: text 
    content: | # this will include new lines to allow paragraphs
      *My whole life I have loved solving problems of all kinds, whether it’s math problems, building furniture, baking, or helping businesses find ways to use their data or measure their mission and vision, I am all in!*
 
      - Raising my 5 children has taught me the value of different perspectives, patience, consistency, and having a higher purpose.
      - Founding a charter school taught me the value of <mark>grit</mark> and that it is possible to make big things happen, against all odds, when you have a clear purpose and the right team by your side.
      - Serving on a school board taught me the importance <mark>integrity</mark> in team, the value of using good, accurate data, <mark>data-driven decision making</mark>, and the importance of a unified vision. 

      #Look at this cool image  
   
      #![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
