# Site
repository: github.com/rachaelssmith
favicon: images/profile_rachael.jpg

# Content configuration version
version: 2

# Personal info
name: Rachael Smith
title: Data Scientist
email: smith.rachael@gmail.com
#website:  

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  rachaelssmith
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: rachael-s-smith
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: mywebsite
  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_rachael.jpg
about_content: | # this will include new lines to allow paragraphs
  
  Hi, my name's Rachael, I am experienced in statistics, business analytics & machine learning.  I love to dream big & am very self driven.  I see challenges as opportunities & have a track record of going above and beyond to accomplish a goal while leading a team along the way.  
 
  Prior to studying Data Science, I founded a leadership charter school & served as Board Vice Chairman for 11 years gaining teamwork & leadership skills. 
  As a board member I valued access to transparent & accurate data to make good decisions, & I understand how blind decision makers can feel when they don't have access to good data.  
  
  I am passionate about understanding my client's challenges & finding the story within the data that can drive businesses to make informed decisions.

  I am most skilled in: <mark>R</mark> & <mark>Python</mark>.  I love math, programming & problem solving. 
  
  I also am skilled at <mark>SQL</mark>, <mark>Machine Learning</mark>, <mark>Google Cloud Platform</mark>, <mark>Excel</mark>, <mark>Power BI</mark>, & <mark>Tableau</mark>.

  Ask me about wake surfing, baking, building furniture, or remodeling.  

content:
 # - title: Projects # Title for the section
  #  layout: list # Type of content section (list/text)
   # content:
    #  - layout: top-middle
     #   title: Research and Business Development Center
      #  link: github.com/sproogen
        # link_text: Project Website
       # additional_links:
  #        - title:  Technical Project Lead
            #icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
        #  Working for Good2Go was a pleasure, what impressed me most is their ability to ask great questions and interest in our growth.
       # description: | # this will include new lines to allow paragraphs
         # - Client is utilizing <mark>Sales Forecasting</mark> tool used in business created in <mark>Power BI</mark>.
          #- Led group of students in <mark>Machine Learning</mark> and <mark>Time Series Prediction</mark> utilizing <mark>R</mark> and <mark>Python</mark>.
          #- Increased workflow efficiency by <mark>wrangling data </mark> in<mark>R</mark> & <mark>SQL</mark> from 40GB file sizes to 1 GB, and from 60 files to a single file.
 
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Brigham Young University - Idaho
        caption: 2018 - 2022
        sub_title: BS | Data Science <br>Minor | Business Analytics<br>Minor | Statistics <br>Certificate | Machine Learning
        quote: >
          BYU-ID encourages students to be proactive learners, become highly skilled, & lift others.
        description: | # this will include new lines to allow paragraphs
          GPA: 3.9 <br><br>
          Relevant Courses:<br>Deep Learning | U of I, Machine Learning, Big Data Analytics, Applied Linear Regression, Data Wrangling & Visualization, Database Design, Linear Algebra & Discrete Math 
 
  - title: Experience  # Title for the section
    layout: list # Type of content section (list/text)
    content:
    
      - layout: left
        title: Micron Technology
        caption: May 2022 - August 2022
        sub_title: Smart Manufacturing and AI <br> Data Science Intern  
        quote: >
          Teams are best when there are strong mentors, collaboration, and trust; sometimes small and simple changes are enough.
        description: | # this will include new lines to allow paragraphs
          - Supported data science team to move existing ML models from internal servers into Google Cloud Platform using best practices for loading, modeling, & saving models in GCP
          - Evaluated, suggested improvements, & presented training on imputers that improved training time & created visualizations showing variations of imputed data to find best K value
          - Created functions to pull data from multiple complex data systems into training data and actual data to help data science team with real time model monitoring for accuracy & drift

      - layout: left
        title: Health Catalyst
        caption: February 2022 - May 2022
        sub_title: Analytics Engineer Intern <br> 
        quote: >
          Navigating databases, joining tables and engineering features creates stronger data for machine learning.
        description: | # this will include new lines to allow paragraphs
          - Predicted patient’s likelihood to respond to outreach with 89% accuracy using machine learning tools in R & international healthcare data, ensuring ethical practices & patient privacy
          - Feature engineered dataset across 20+ tables with custom SQL functions to join and aggregate data that can be applied across multiple countries and healthcare systems
          - Revenue attributed to the process exceeded $1M over 3 months in directly attributable revenue, results helped to secure a multi-year, multi-million-dollar engagement

      - layout: left
        title: Good 2 Go
        caption: May 2021 - October 2021
        sub_title: Data Science Finance Intern
        quote: >
          Working Remotely is effective when you have clear expectations, strong communication and a google search bar.
        description: | # this will include new lines to allow paragraphs
          - Built an exponential smoothing time series forecasting interactive Power BI tool to predict   next quarter’s unique fuel volume and retail sales for 60 locations across 8 states
          - Solved complex time series challenges using SQL and R code caused by multiple locations, differing start & end dates, partial months, traditional calendar & 454 retail calendar dates

      - layout: left
        title: Research & Business Development Center
        caption: January 2021 - April 2021
        sub_title: Technical Project Lead 
        quote: >
          Understanding the client's needs while leading a team showed me the value of collaboration and good communication.
        description: | # this will include new lines to allow paragraphs
          - Led 2 projects/teams of 6 associates; managed deadlines, articulated and set clear goals, collaborated between client & team, proposed additional steps, & presented final analysis
          - Engineered features leveraging diverse data to perform statistical analysis of 25K locations comparing client metrics to competitors, used distance matrices to find nearest competitors
          - Showed significant linear correlation of cell phone location data & client sales

      - layout: left
        title: Brigham Young University Idaho
        caption: September 2020 - December 2020
        sub_title: Intermediate Statistics <br> Teacher's Assistant & Tutor
        quote: >
          Tutoring students helped me become a better student, I loved helping others succeed!
        description: | # this will include new lines to allow paragraphs
          - Tutored intermediate-level statistical students in modeling and analysis in R

      - layout: left
        title: Research & Business Development Center
        caption: September 2020 - December 2020
        sub_title: Consultant
        quote: >
          I was impressed by our client's ability to ask great questions & their interest in our growth.
        description: | # this will include new lines to allow paragraphs
          - Wrangled 60 GB raw data using SQL and R to visualize the effect of Covid-19 on sales.
          
  - title: Volunteer # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Village<br>Charter School
        #link: thevillagecharter.org
        #link_text: thevillagecharter.org
        sub_title: Founder <br> Board Vice Chairman
        caption: May 2009 - June 2020
        quote: >
          I developed a passion for education when I realized that teachers can either ignite a love of learning in students or distinguish it.
        description: | # this will include new lines to allow paragraphs
          - Achieved Lighthouse Recognition as a Leader in Me Lighthouse School using Franklin Covey's 7 Habits of Highly Successful People.
          - Approved annual budgets, oversaw board development, open meeting law & school policies, & managed relationship with bondholders & authorizer.  
          - Recruited 3 exceptional administrators, graduated nine 8th grade classes, & served 1000s of K-8 students in Idaho. 
          - Designed, Implemented and Secured Authorization for a Leadership Charter School, focused on Hands-on Learning & the 7 Habits of Highly Effective People.  
          - Awarded and monitored use of over $600K in charter-start grants, established policies & protocols for startup

  - title: A Little More About Me
    layout: text 
    content: | # this will include new lines to allow paragraphs
      - Raising 5 children is teaching me the value of different perspectives, patience, consistency, and having a higher purpose
      - Founding a charter school is like starting any business, and taught me the value of grit & that it is possible to make big things happen, against all odds, when you have a clear vision & the right team by your side
      - Serving on a school board taught me leadership and presentation skills, the importance integrity in teams, the value of using good, accurate data, data-driven decision making, and the importance of a unified vision 
      - Going back to college has shown me that it is never too late to pursue your dreams, & it just as valuable to ask questions as to answer them
      <br>
      <br>*My whole life I have loved solving problems of all kinds, whether it’s math problems, building furniture, baking, or helping businesses find ways to use their data or measure their mission and vision, I am all in! I am always looking to connect with clients who feel I can add value to their business.* 
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
