# Site
repository: github.com/rachaelssmith
favicon: images/profile_rachael.jpg

# Content configuration version
version: 2

# Personal info
name: Rachael Smith
title: Data Scientist
email: smith.rachael@gmail.com
#website:  

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  rachaelssmith
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: rachael-s-smith
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: mywebsite
  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_rachael.jpg
about_content: | # this will include new lines to allow paragraphs
  
  Hi, my name's Rachael and I am experienced in statistics, business analytics and machine learning.  I love to dream big and am very self driven.  I see challenges as opportunities and I have a track record of going above and beyond to accomplish a goal and leading a team along the way.  
 
  Prior to studying Data Science, I founded a charter school and served as a Board Vice Chairman for 10 years gaining teamwork and leadership skills. 
  As a board member, I valued access to transparent and accurate data to make good decisions, I understand how blind you can feel as a decision maker when you don't have access to good data.  
  
  I am passionate about understanding my client's challenges and finding the story within the data that can drive businesses to make informed decisions.

  I am most skilled in: <mark>R</mark> and <mark>Python</mark>.  I love math, programming & problem solving. 
  
  I also am skilled at <mark>SQL</mark>, <mark>Machine Learning</mark>, <mark>Excel</mark>, <mark>Power BI</mark>, <mark>R</mark>, & <mark>Tableau</mark>.

content:
 # - title: Projects # Title for the section
  #  layout: list # Type of content section (list/text)
   # content:
    #  - layout: top-middle
     #   title: Research and Business Development Center
      #  link: github.com/sproogen
        # link_text: Project Website
       # additional_links:
  #        - title:  Technical Project Lead
            #icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
        #  Working for Good2Go was a pleasure, what impressed me most is their ability to ask great questions and interest in our growth.
       # description: | # this will include new lines to allow paragraphs
         # - Client is utilizing <mark>Sales Forecasting</mark> tool used in business created in <mark>Power BI</mark>.
          #- Led group of students in <mark>Machine Learning</mark> and <mark>Time Series Prediction</mark> utilizing <mark>R</mark> and <mark>Python</mark>.
          #- Increased workflow efficiency by <mark>wrangling data </mark> in<mark>R</mark> & <mark>SQL</mark> from 40GB file sizes to 1 GB, and from 60 files to a single file.
 
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Brigham Young University - Idaho
        caption: 2018 - 2022
        sub_title: BS | Data Science <br> Minor | Business Analytics <br> Certificate | Machine Learning
        quote: >
          BYU-ID encourages students to be proactive learners, become highly skilled, & lift others.
        description: | # this will include new lines to allow paragraphs
          *GPA | 3.88* <br>
          As a data science student, My time at BYU-ID has ignited a spark for machine learning and statistical analysis. I also learned how to navigate personal goals, collaborate on team projects, and work with tight deadlines. 
 
  - title: Data Science Lead  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Research & Business Development Center
        caption: January 2021 - April 2021
        sub_title: Technical Project Lead <br> Good2Go Forecasting
        quote: >
          Understanding the client's needs while leading a team showed me the value of collaboration and good communication.
        description: | # this will include new lines to allow paragraphs
          - Client is utilizing sales forecasting tool used in business created in Power BI, using R scripts.
          - Led group of students in machine learning and Time Series Prediction utilizing R and Python, including scikit-learn, holt winters, and ARIMA.
          - Increased workflow efficiency by wrangling data in R & SQL from 40GB file sizes to 1 GB, and from 60 files to a single file.

      - layout: left
        title: Brigham Young University Idaho
        caption: September 2020 - December 2020
        sub_title: Intermediate Statistics <br> Teacher's Assistant & Tutor
        quote: >
          Tutoring students helped me become a better student, I loved helping others succeed!
        description: | # this will include new lines to allow paragraphs
          - Supported students in understanding statistical testing, analysis, and R Markdowns.
          - Provided expertise in statistical modeling and data wrangling & data visualization using ggplot & tidyverse. 

  - title: Data Science Projects  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Research & Business Development Center
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Student Consultant <br> Good2Go & Pinnacle
        caption: September 2020 - December 2020
        quote: >
          I was impressed by our client's ability to ask great questions & their interest in our growth.
        description: | # this will include new lines to allow paragraphs
          - Created interactive visualization in R and a Power BI dashboard that showed client effect of sales from business closures due to Covid-19.
          - Solved challenges as a team including good data visualization, working with large datasets, and collaborating to find the best visual solution to a client's questions.


  - title: Service & Experience  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Village Charter School
        link: thevillagecharter.org
        link_text: thevillagecharter.org
        sub_title: Founder <br> Board Vice Chairman
        caption: May 2009 - June 2020
        quote: >
          I didn't know I had a passion for education until I realized that a child's teacher can ignite the love of learning, or distinguish it. 
        description: | # this will include new lines to allow paragraphs
          Vice Chairman 
          - Achieved Lighthouse Recognition as a Leader in Me Lighthouse School with Franklin Covey.
          - Oversaw board development, open meeting law and school policies, managed relationship with bondholders and authorizer.  
          - Bonded, and renovated permanent facilityrenovated 32,000 square foot facility.
          - Recruited 3 exceptional administrators, grew enrollment from 300-500 students, graduated nine 8th grade classes, served 1000s of K-8 students in Idaho. 
         Founder
          - Designed, Implemented and Secured Authorization for a Leadership Charter School, focused on Hands-on Learning, Challenging and Engaging all Students, Whole Child Education and the 7 Habits of Highly Effective People.  
          - Awarded and monitored use of over $600K in charter-start grants. 
          - Hired staff, recruited students, Held public meetings and events, monitored budget and grant funding, established policies and protocols for startup.

  - title: A Little More About Me
    layout: text 
    content: | # this will include new lines to allow paragraphs
      - Raising 5 children is teaching me the value of different perspectives, patience, consistency, and having a higher purpose.
      - Founding a charter school taught me the value of grit and that it is possible to make big things happen, against all odds, when you have a clear purpose and the right team by your side.
      - Serving on a school board taught me the importance integrity in teams, the value of using good, accurate data, data-driven decision making, and the importance of a unified vision. 
      - Going back to college has taught me that it is never too late to pursue your dreams.
      <br>
      <br>*My whole life I have loved solving problems of all kinds, whether it’s math problems, building furniture, baking, or helping businesses find ways to use their data or measure their mission and vision, I am all in! I am always looking to connect with clients who feel I can add value to their business.* 
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
